"""initial squashed

Revision ID: 0000
Revises:
Create Date: 2025-02-19 00:00:00.000000+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import msm.apiserver.db.types

# revision identifiers, used by Alembic.
revision: str = "0000"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create sequence for boot_source
    op.execute(
        "CREATE SEQUENCE source_id_sequence START WITH 2 INCREMENT BY 1"
    )

    # Create config table
    op.create_table(
        "config",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore[no-untyped-call]
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )

    # Create setting table
    op.create_table(
        "setting",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore[no-untyped-call]
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )

    # Create site table
    op.create_table(
        "site",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column(
            "coordinates", msm.apiserver.db.types.Point(), nullable=True
        ),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cluster_uuid", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_uuid"),
    )
    op.create_index(
        op.f("ix_site_accepted"), "site", ["accepted"], unique=False
    )
    op.create_index(op.f("ix_site_name"), "site", ["name"], unique=False)

    # Create user table
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("auth_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_auth_id"), "user", ["auth_id"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=True
    )

    # Create boot_source table
    op.create_table(
        "boot_source",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Sequence("source_id_sequence", start=2, increment=1),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("keyring", sa.Text(), nullable=True),
        sa.Column("sync_interval", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create site_data table
    op.create_table(
        "site_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("machines_allocated", sa.Integer(), nullable=False),
        sa.Column("machines_deployed", sa.Integer(), nullable=False),
        sa.Column("machines_ready", sa.Integer(), nullable=False),
        sa.Column("machines_error", sa.Integer(), nullable=False),
        sa.Column("machines_other", sa.Integer(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
    )

    # Create token table
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("auth_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("expired", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_auth_id"), "token", ["auth_id"], unique=True
    )
    op.create_index(
        op.f("ix_token_audience_purpose"),
        "token",
        ["audience", "purpose"],
        unique=False,
    )

    # Create boot_source_selection table
    op.create_table(
        "boot_source_selection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_source_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("os", sa.Text(), nullable=False),
        sa.Column("release", sa.Text(), nullable=False),
        sa.Column("arch", sa.Text(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_source_id"], ["boot_source.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create boot_asset table
    op.create_table(
        "boot_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_source_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("os", sa.Text(), nullable=False),
        sa.Column("release", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("krel", sa.Text(), nullable=True),
        sa.Column("codename", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("arch", sa.Text(), nullable=False),
        sa.Column("subarch", sa.Text(), nullable=True),
        sa.Column("compatibility", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("flavor", sa.Text(), nullable=True),
        sa.Column("base_image", sa.Text(), nullable=True),
        sa.Column("bootloader_type", sa.Text(), nullable=True),
        sa.Column("eol", sa.DateTime(timezone=True), nullable=True),
        sa.Column("esm_eol", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_source_id"], ["boot_source.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "boot_source_id", "os", "release", "arch", "subarch"
        ),
    )

    # Create boot_asset_version table
    op.create_table(
        "boot_asset_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_asset_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_asset_id"], ["boot_asset.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("boot_asset_id", "version"),
    )

    # Create boot_asset_item table
    op.create_table(
        "boot_asset_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("boot_asset_version_id", sa.Integer(), nullable=True),
        sa.Column("ftype", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("source_package", sa.Text(), nullable=True),
        sa.Column("source_version", sa.Text(), nullable=True),
        sa.Column("source_release", sa.Text(), nullable=True),
        sa.Column("bytes_synced", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boot_asset_version_id"],
            ["boot_asset_version.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("boot_asset_version_id", "ftype", "path"),
    )

    # Create the materialized view
    op.execute(
        """
        CREATE MATERIALIZED VIEW images_index AS
        SELECT DISTINCT ON (asset.boot_source_id, ver_item.ftype, ver_item.path)
            asset.id,
            asset.boot_source_id,
            asset.kind,
            asset.label,
            asset.os,
            asset.arch,
            asset.release,
            asset.asset_version,
            asset.krel,
            asset.codename,
            asset.title,
            asset.subarch,
            asset.compatibility,
            asset.flavor,
            asset.base_image,
            asset.bootloader_type,
            asset.eol,
            asset.esm_eol,
            asset.signed,
            ver_item.version,
            ver_item.ftype,
            ver_item.sha256,
            ver_item.path,
            ver_item.file_size,
            ver_item.bytes_synced,
            ver_item.source_package,
            ver_item.source_version,
            ver_item.source_release
        FROM
            (
                SELECT DISTINCT ON (boot_asset.os, boot_asset.release, boot_asset.arch)
                    source.priority,
                    boot_asset.id,
                    boot_asset.boot_source_id,
                    boot_asset.kind,
                    boot_asset.label,
                    boot_asset.os,
                    boot_asset.arch,
                    boot_asset.release,
                    boot_asset.version AS asset_version,
                    boot_asset.krel,
                    boot_asset.codename,
                    boot_asset.title,
                    boot_asset.subarch,
                    boot_asset.compatibility,
                    boot_asset.flavor,
                    boot_asset.base_image,
                    boot_asset.bootloader_type,
                    boot_asset.eol,
                    boot_asset.esm_eol,
                    boot_asset.signed
                FROM
                    (
                        boot_asset
                        JOIN
                        (
                            SELECT bs.id, bs.priority
                            FROM boot_source bs
                        ) AS source
                        ON boot_asset.boot_source_id = source.id
                    )
                ORDER BY boot_asset.os, boot_asset.release, boot_asset.arch, source.priority DESC
            ) as asset
        JOIN
            (
                (
                    SELECT DISTINCT ON (v.boot_asset_id) v.id, v.version, v.boot_asset_id
                    FROM boot_asset_version v
                    ORDER BY v.boot_asset_id, v.version DESC
                ) AS ver
                JOIN boot_asset_item item
                ON ver.id = item.boot_asset_version_id
            ) as ver_item
        ON ver_item.boot_asset_id = asset.id
        """
    )

    # Create the unique index on materialized view
    op.execute(
        """
        CREATE UNIQUE INDEX image_item ON images_index (os, release, arch, path)
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the index first
    op.execute("DROP INDEX IF EXISTS image_item")

    # Drop the materialized view
    op.execute("DROP MATERIALIZED VIEW IF EXISTS images_index")

    # Drop tables in reverse order
    op.drop_table("boot_asset_item")
    op.drop_table("boot_asset_version")
    op.drop_table("boot_asset")
    op.drop_table("boot_source_selection")
    op.drop_index(op.f("ix_token_audience_purpose"), table_name="token")
    op.drop_index(op.f("ix_token_auth_id"), table_name="token")
    op.drop_table("token")
    op.drop_table("site_data")
    op.drop_table("boot_source")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_auth_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_site_name"), table_name="site")
    op.drop_index(op.f("ix_site_accepted"), table_name="site")
    op.drop_table("site")
    op.drop_table("setting")
    op.drop_table("config")

    # Drop sequence
    op.execute("DROP SEQUENCE IF EXISTS source_id_sequence")

    # ### end Alembic commands ###
