"""site_profiles

Revision ID: 0001
Revises: 0000
Create Date: 2026-04-06 19:51:07.391697+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = "0000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ID sequence for site profile ID, since ID=1 is default profile.
    op.execute(
        "CREATE SEQUENCE site_profile_id_sequence START WITH 2 INCREMENT BY 1"
    )

    op.create_table(
        "site_profile",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Sequence("site_profile_id_sequence", start=2, increment=1),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("selections", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "global_config",
            postgresql.JSONB(astext_type=sa.Text()),  # type: ignore[no-untyped-call]
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_profile")),
        sa.UniqueConstraint("name", name=op.f("uq_site_profile_name")),
    )
    op.create_table(
        "site_state_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "STARTED", "COMPLETE", "FAILED", "UNKNOWN", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "selections_status",
            sa.Enum(
                "STARTED", "COMPLETE", "FAILED", "UNKNOWN", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "global_config_status",
            sa.Enum(
                "STARTED", "COMPLETE", "FAILED", "UNKNOWN", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "image_sync_status",
            sa.Enum(
                "STARTED", "COMPLETE", "FAILED", "UNKNOWN", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column("errors", sa.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["site.id"],
            name=op.f("fk_site_state_status_site_id_site"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_state_status")),
        sa.UniqueConstraint(
            "site_id", name=op.f("uq_site_state_status_site_id")
        ),
    )
    op.add_column(
        "site",
        sa.Column("known_config_options", sa.ARRAY(sa.Text()), nullable=False),
    )
    op.add_column("site", sa.Column("version", sa.Text(), nullable=True))
    op.add_column(
        "site", sa.Column("trigger_image_sync", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "site", sa.Column("site_profile_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_site_site_profile_id_site_profile"),
        "site",
        "site_profile",
        ["site_profile_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index("ix_token_audience_purpose", table_name="token")
    op.create_index(
        op.f("ix_token_audience"),
        "token",
        ["audience", "purpose"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_audience"), table_name="token")
    op.create_index(
        "ix_token_audience_purpose",
        "token",
        ["audience", "purpose"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_site_site_profile_id_site_profile"),
        "site",
        type_="foreignkey",
    )
    op.drop_column("site", "site_profile_id")
    op.drop_column("site", "trigger_image_sync")
    op.drop_column("site", "version")
    op.drop_column("site", "known_config_options")
    op.drop_table("site_state_status")
    op.drop_table("site_profile")

    # Drop sequence
    op.execute("DROP SEQUENCE IF EXISTS site_profile_id_sequence")

    # ### end Alembic commands ###
