"""add provider id column to user

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-09 13:11:28.229658+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("provider_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_user_provider_id_oidc_provider"),
        "user",
        "oidc_provider",
        ["provider_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_provider_id_oidc_provider"), "user", type_="foreignkey"
    )
    op.drop_column("user", "provider_id")
    # ### end Alembic commands ###
